version: '3.8'

services:
  app:
    build:
      context: .
      target: ${TARGET:-dev}
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/user

  db:
    image: postgres:15
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
